force-app/main/default/objects/Actor__c/Actor__c.object-meta.xml
<CustomObject>
    <label>Actor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MovieActor__c/MovieActor__c.object-meta.xml
<CustomObject>
    <label>Movie Actor</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Movie Actor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movie Actors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MovieActor__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <label>Actor</label>
    <referenceTo>Actor__c</referenceTo>
    <relationshipLabel>Movie Actors</relationshipLabel>
    <relationshipName>MovieActors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MovieActor__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Movie Actors</relationshipLabel>
    <relationshipName>MovieActors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ActorTriggerHandler.cls
public with sharing class ActorTriggerHandler extends TriggerHandler {
    private Map<Id, Actor__c> oldActorMap;
    public ActorTriggerHandler() {
        this.oldActorMap = (Map<Id, Actor__c>) Trigger.oldMap;
    }

    public override void afterDelete(){
        Map<Id, MovieActor__c> movieActorLst = new Map<Id, MovieActor__c>([SELECT Id, Actor__c, Movie__c FROM MovieActor__c limit 50000]);
        MovieActorTriggerHelper.calculateGenderPercentage(movieActorLst);
    }
}